// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Item struct {
	ID      int32
	UserID  int32
	Value   string
	Foriegn interface{}
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
}
